### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by calebboyd** [calebboyd/xbin#1]
- [x] Complete native module example
- [x] Support instant rebuilds
- [x] Add download flag to support prebuilt binaries
- [ ] ~Add `--update` flag (like `--download` -- but from a file, not a url)~
- [ ] ~Add plugin support~
- [ ] ~Add docker tests~
- [ ] ~Convert source to TypeScript~
- [ ] ~~Add source map support~~?
